src/onnxruntime.cc
In relation with https://github.com/triton-inference-server/backend/pull/20
=> Use advanced version of ProcessTensor()

src/onnxruntime.cc
Adding ragged batch support for onnxruntime backend
=> add ragged batch support for ort backend

src/onnxruntime.cc
Enable iobinding for onnxruntime backend
=> enable iobinding

src/onnxruntime.cc
This change always binds output to cpu allocator. Ideally triton should add an API to query the preferred location for the output. Without this information we can incur extra copies if we bind output to gpu but the preferred location is cpu.
=> always bind output to cpu

src/onnxruntime.cc
See PR on backend repo as reference https://github.com/triton-inference-server/backend/pull/28
=> Modify backend to be host policy aware

src/onnxruntime.cc
Fixes the support for STRING data type in implicit state.
=> Fix string state support

src/onnxruntime.cc
Cherry picking the changes to r22.01 branch.
=> Fix string state support (#92)

src/onnxruntime.cc
This PR enables io-binding for outputs.
=> enable io binding for outputs

README.md
Models won't load if using this configuration
=> Missing curly bracket

src/onnxruntime.cc
* Default to load model on GPU when instance kind is not specified and autocomplete is used
* Add compile flags
* cleanup
* review edits
=> Default to load model on GPU when instance kind is not specified  (#112)

src/onnxruntime_loader.cc
This reverts commit 05e038345459dcc4d571a6a6d0941ed8ceb833c4.
=> Revert "Fixes tensorrt cache being regenerated on path change (#126)"

src/onnxruntime.cc, src/onnxruntime_loader.cc
Related PR: https://github.com/triton-inference-server/core/pull/165
=> Serialize ModelInstanceState constructor for parallel model loading

tools/gen_ort_dockerfile.py
* Change CMAKE version
* Update TensorRT flag condition
* Allow execute as a root
* Set CMAKE to pull latest version
* adding WAR for installing openvino 2022.1 on ubuntu22.04
* rename openvino install directory
---------
=> Update `main` post-23.05 release

tools/gen_ort_dockerfile.py
* Update ORT generator version
* Linking against ORT version
=> Update build instructions to support ORT 1.16.0 (#212)

src/onnxruntime.cc, src/onnxruntime_utils.h
cherry-pick https://github.com/triton-inference-server/onnxruntime_backend/pull/215
=> Fix input check for initializer input (#215)

CMakeLists.txt, tools/gen_ort_dockerfile.py
Bring iGPU build refactor into main
=> iGPU build refactor (#224)

tools/gen_ort_dockerfile.py
Related PRs:
* https://github.com/triton-inference-server/server/pull/6880
* https://github.com/triton-inference-server/openvino_backend/pull/63
=> OpenVINO 2023.3.0

tools/gen_ort_dockerfile.py
* Use OpenVINO 2023.3.0
* OV 2023.3.0
=> OpenVINO 2023.3.0 (#238)

src/onnxruntime.cc, tools/gen_ort_dockerfile.py
* Change default flag value for OpenVINO
* Change default flag value for OpenVINO
=> Change default flag value for OpenVINO (#252)

tools/gen_ort_dockerfile.py
This change include following commit:
https://github.com/microsoft/onnxruntime/pull/22374
=> Enable support for TensoRT 10.5

tools/gen_ort_dockerfile.py
This reverts commit d5fe74f73109425a09ed3332029d270e11da5311.
https://github.com/triton-inference-server/server/pull/7721
https://github.com/triton-inference-server/core/pull/403
=> Revert "Remove unsupported compute capabilities (#275)"

tools/gen_ort_dockerfile.py
This reverts commit 2ddd44cea4fbeae025fe643685abdb3b26d68ca4.
=> Reapply "Remove unsupported compute capabilities (#275)"

CMakeLists.txt, tools/gen_ort_dockerfile.py
This PR is subset of changes which need to be carried over to the `main` branch after the release
=> Update `main` branch post 24.11

CMakeLists.txt, cmake/download_onnxruntime.cmake, tools/gen_ort_dockerfile.py
- **Update README and versions for 2.53.0 / 24.12 (#288)**
- **Update OpenVINO to 2024.5 (#287)**
- **Extract archive in different location (#289)**
=> Upadate default branch post 24.12

src/onnxruntime.cc
=> fix: Set correct device ID with TRT EP
