triton-inference-server/onnxruntime_backend

- src/onnxruntime.cc
After all the OrtValues returned from GetBoundOutputValues are individually released, the output buffer which is allocated using the specified instance of the allocator must be freed using the same allocator.
> Fixing mem leak reported in #45

- tools/gen_ort_dockerfile.py
Enables trt 8.0 for ORT backend. TRT 8.0 support is not yet available in a released version of ort therefore using tensorrt-8.0 branch in ort instead of the rel-* branches until ORT 1.9 release.
> ort trt update

- README.md
- src/onnxruntime.cc
Enabling following options for TRT EP
- ORT_TENSORRT_INT8_ENABLE
- ORT_TENSORRT_INT8_CALIBRATION_TABLE_NAME
- ORT_TENSORRT_INT8_USE_NATIVE_CALIBRATION_TABLE
- ORT_TENSORRT_ENGINE_CACHE_ENABLE
- ORT_TENSORRT_CACHE_PATH
> enable more trt options

- CMakeLists.txt
- tools/gen_ort_dockerfile.py
Targeting Triton 21.09 release
> explicitly add cmake cuda architectures for windows and remove use_openmp build option

- src/onnxruntime.cc
- src/onnxruntime_utils.h
**Description**
Make OrtRun return error if any. Besides, return early if OrtRun fails.
The full server log after this fix: 
[server_log.txt](https://github.com/triton-inference-server/onnxruntime_backend/files/7214715/server_log.txt)
The sever will last even if ortrun fails:
```
I0921 20:09:01.361565 1 grpc_server.cc:4111] Started GRPCInferenceService at 0.0.0.0:8001
I0921 20:09:01.361802 1 http_server.cc:2803] Started HTTPService at 0.0.0.0:8000
I0921 20:09:01.403248 1 http_server.cc:162] Started Metrics Service at 0.0.0.0:8002
2021-09-21 20:09:26.315850258 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Gather node. Name:'bert/embeddings/GatherV2' Status Message: indices element out of data bounds, idx=-1420042007188224409 must be within …
```
> Return early if ortrun bumps into a inference error

- CMakeLists.txt
- tools/gen_ort_dockerfile.py
Enable "Debug", "Release" and "RelWithDebInfo" ORT builds on linux. Simply use the CMAKE_BUILD_TYPE var to choose the desired config.
> enable ort debug builds on linux

- README.md
Parameter JSON examples that refer to string_value couldn't be parsed correctly.
> Fix model config examples using string_value

- README.md
- src/onnxruntime.cc
Adding inter_op_num_threads and execution_mode config options. They were requested for olive + MA integration by the Olive team.
> add more config options for ort

- CMakeLists.txt
- tools/gen_ort_dockerfile.py
Right now libtriton_onnxruntime.so has a strict version dependency on libonnxruntime.so. This makes it difficult to replace ort binaries in released containers for easy experimentation. Current solution is to build triton-ort backend which is not always possible.
> remove version dependency on libonnxruntime.so

- CMakeLists.txt
- tools/gen_ort_dockerfile.py
Triton 21.12 will include TRT 8.2. This PR is in preparation for this change.
With this change we let the user to provide a branch\tag for onnx-tensorrt parser repo "TRITON_ONNX_TENSORRT_REPO_TAG "
If this tag is specified we simply use this to build ORT. If nothing is specified then we use the defaults listed in ORT_TO_TRTPARSER_VERSION_MAP specific to the ort and trt version being built. If this map does not have an entry for the ort version and trt version combo then we simply use the default branch\tag which ort uses.
This is to enable support for versions of TRT which ORT release does not support yet. 
Note: I have tested this on linux but not windows.
> update tensorrt parser to support TRT 8.2

- src/onnxruntime.cc
- src/onnxruntime_utils.h
Uses a macro form the common backend repo added by this [PR](https://github.com/triton-inference-server/backend/pull/51).
Note: The fail count being reported correctly with the fix.
###After:
```
curl localhost:8000/v2/models/stats
{"model_stats":[{"name":"onnx_float32_float32_float32","version":"1","last_inference":0,"inference_count":0,"execution_count":0,"inference_stats":{"success":{"count":0,"ns":0},"fail":{"count":1,"ns":2919154},"queue":{"count":0,"ns":0},"compute_input":{"count":0,"ns":0},"compute_infer":{"count":0,"ns":0},"compute_output":{"count":0,"ns":0}},"batch_stats":[]}]}
```
###Before:
```
curl localhost:8000/v2/models/stats
{"model_stats":[{"name":"onnx_float32_float32_float32","version":"1","last_inference":0,"inference_count":0,"execution_count":0,"inference_stats":{"suc …
```
> Fix error handling to include failed counts in infer stat

- tools/gen_ort_dockerfile.py
After adding in libonnx_proto.so and the corr libprotobufs.so files ORT throws the error
```
model_repository_manager.cc:1155] failed to load 'resnet50_cpu_openvino' version 1: Internal: onnx runtime error 6: Exception during initialization: /workspace/onnxruntime/onnxruntime/core/providers/openvino/backend_utils.cc:143 std::shared_ptr<InferenceEngine::CNNNetwork> onnxruntime::openvino_ep::backend_utils::CreateCNNNetwork(const onnx::ModelProto&, const onnxruntime::openvino_ep::GlobalContext&, const onnxruntime::openvino_ep::SubGraphContext&, std::map<std::__cxx11::basic_string<char>, std::shared_ptr<ngraph::Node> >&) [OpenVINO-EP] [OpenVINO-EP] Exception while Reading network: Unknown model format! Cannot find reader for the model and read it. Please check that reader library exists in …
```
> libonnx_proto.so is needed for OV 2021.4 for onnx OV execution

- README.md
- src/onnxruntime.cc
Addresses https://github.com/triton-inference-server/onnxruntime_backend/issues/103 and https://github.com/triton-inference-server/onnxruntime_backend/issues/102 (partially).
Tests are checked in here https://github.com/triton-inference-server/server/pull/4069.
> Expose memory and arena configs.

- src/onnxruntime.cc
The root cause for the segfault was that when instance kind is KIND_CPU and the OutputBufferQuery returns a GPU memory, `cuda_allocator_info_` is a nullptr and will lead to a segfault. Stacktrace of the segfault:
```
#1  0x00007f8338fa44d9 in triton::backend::onnxruntime::ModelInstanceState::ProcessRequests (this=0x7f80d80115c0, requests=0x7f81580440c0, request_count=1) at /workspace/onnxruntime_backend/src/onnxruntime.cc:1630
#2  0x00007f8338fb10c6 in triton::backend::onnxruntime::TRITONBACKEND_ModelInstanceExecute (instance=0x7f80d8015c30, requests=0x7f81580440c0, request_count=1) at /workspace/onnxruntime_backend/src/onnxruntime.cc:2600
```
> Fix L0_infer_cudashm failure

- src/onnxruntime.cc
This PR fixes onnxruntime's autocomplete to check the instance(s) kind of the of the model before loading. If no GPU instance groups are found then autocomplete will set the kind to CPU before loading the model.
> Fix Autocomplete To Use CPU When No GPU Found

- src/onnxruntime_loader.cc
OrtEnv gets created twice in onnx_loader. This causes its refcount to
increase to 2. Due to this when ReleaseEnv is called inside ~OnnxLoader,
it does nothing other than decrease the refcount to 1. Next when all the libraries
are unloaded the [openvino global context ptr](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/openvino/backend_manager.cc#L16) gets unloaded first followed by OrtEnv's
destructor which now actually does useful work trying to delete the openvno ctx ptr
which is not valid any more causing memory corruption.
> Fix OrtEnv creation causing server to hang during shutdown.

- README.md
- src/onnxruntime.cc
- src/onnxruntime_loader.cc
Onnxruntime backend now makes use of the default max-batch-size value which is passed to it. If the final max-batch-size is greater than 1 then the backend turns on dynamic batching if no other schedulers are found.
> Autocomplete now makes use of the default-max-batch-size

- src/onnxruntime_loader.cc
Onnxruntime uses the path as a hash for the tensorrt cache, passing a binary avoids this and works as intended.
Fixes https://github.com/triton-inference-server/server/issues/4587
> Fixes tensorrt cache being regenerated on path change

- tools/gen_ort_dockerfile.py
Use special ORT branch 'tensorrt-8.5ea' brought in by the ORT 1.12.1 release to make use of the built-in tensorrt parser.
> Use special ORT branch 'tensorrt-8.5ea' brought in by the ORT 1.12.1 release to make use of the built-in tensorrt parser.

- tools/gen_ort_dockerfile.py
Onnxruntime now supports CUDA 11.8 which is able to compile for compute capability 9.0. This PR makes use of this advancement to include a fat binary for compute capability 9.0 rather than onnxruntime needing to JIT on initialization. This enhancement improves startup times as described by [this issue](https://github.com/microsoft/onnxruntime/issues/10746).
> Adding cuda arch 90 to Onnxruntime compilation

- tools/gen_ort_dockerfile.py
The fix is available in ORT 1.14.1 release which we are using.
https://github.com/microsoft/onnxruntime/blob/v1.14.1/onnxruntime/contrib_ops/cuda/bert/attention_impl.cu#L31
> Remove the cherry-pick fix

- CMakeLists.txt
- tools/gen_ort_dockerfile.py
Since Jetson's CUDA version now supports compute_90, build for that architecture as well.
- Remove special handling code to exclude compute_90 architecture for Jetson.
> Include compute_90 architecture build on Jetson

- CMakeLists.txt
- tools/gen_ort_dockerfile.py
server: https://github.com/triton-inference-server/server/pull/6031
openvino_backend: https://github.com/triton-inference-server/openvino_backend/pull/57
Some notes on the upgrade:
- The `tbb.so` library no longer needs to be linked, so it is removed from the build.
- There are quite a few extra libraries built but not required for CPU acceleration (i.e. PaddlePaddle), so only the required libraries are included to save final image size.
> OpenVINO 2023.0.0

- src/onnxruntime.cc
The issue was that the runtime inference would always return a CPU tensor when warm-up is enabled. This occurred because we recorded the output memory type using the first request. Since the warm-up is the first request to the model and always allocates CPU memory for the output, it incorrectly recorded the memory type for the output.
This PR fixes the logic so that the warm-up inference does not affect the actual memory type of the output tensor.
Testing: https://github.com/triton-inference-server/server/pull/6033
> Fix the memory type of output tensor when warm-up is enabled

- tools/gen_ort_dockerfile.py
This PR includes the `libtbb.so` into the backend build, in case the container does not have the library installed.
Related PR: https://github.com/triton-inference-server/openvino_backend/pull/58
> Include libtbb.so

- src/onnxruntime.cc
Main area of concern appears to be this [model_state->LoadModel](https://github.com/triton-inference-server/onnxruntime_backend/blob/main/src/onnxruntime.cc#L366-L665) call made by [each instance](https://github.com/triton-inference-server/onnxruntime_backend/blob/d98c883455fd9ad1ccf179590afe7c186d0f6c41/src/onnxruntime.cc#L1034-L1036).
However, this function appears well protected, with most actions being done on a [cloned session for each instance](https://github.com/triton-inference-server/onnxruntime_backend/blob/d98c883455fd9ad1ccf179590afe7c186d0f6c41/src/onnxruntime.cc#L403-L408), and a called out [area of concern for OpenVINO](https://github.com/triton-inference-server/onnxruntime_backend/blob/d98c883455fd9ad1ccf179590afe7c186d0f6c41/src/onnxruntime.cc#L649-L655) which is already …
> Enable parallel instance loading backend attribute

- src/onnxruntime.cc
testing: https://github.com/triton-inference-server/server/pull/6343
>  Add scalar support in ORT backend

- README.md
- src/onnxruntime.cc
Please let me know if it would be better to use a different value instead of 2.
This change allows users to set optimization->graph->level to DISABLE_ALL by setting 2. The reason for this is that sometimes specially when using a triton server for serving multiple models, we prefer users to optimize the model offline instead of online. This allows us to disable optimization greatly speeding up load time into triton onnxruntime backend.
This is my first contribution here, so please do let me know if I should change anything or add more tests. Given the code is 2 lines, I didn't initially add it.
> Add option to set ORT_DISABLE_ALL as optimization

- README.md
- src/onnxruntime.cc
This PR enables more ORT-TRTEP v2 options:
| trt_max_partition_iterations          |
| :------------------------------------ |
| trt_min_subgraph_size                 |
| trt_dla_enable                        |
| trt_dla_core                          |
| trt_engine_cache_prefix               |
| trt_dump_subgraphs                    |
| trt_force_sequential_engine_build     |
| trt_context_memory_sharing_enable     |
| trt_layer_norm_fp32_fallback          |
| trt_timing_cache_enable               |
| trt_force_timing_cache                |
| trt_detailed_build_log                |
| trt_build_heuristics_enable           |
| trt_sparsity_enable                   |
| trt_builder_optimization_level        |
| trt_auxiliary_streams                 |
| trt_tactic_sources                    | …
> [TensorRT EP] Enable more trt options

- src/onnxruntime.cc
- tools/gen_ort_dockerfile.py
Tested with OV 2024.X. This PR should be merged after ORT upgraded to 1.18.
> Remove openvino hard-coded versioning in onnxruntime backend build

- README.md
- src/onnxruntime.cc
This PR is based on https://github.com/triton-inference-server/onnxruntime_backend/pull/242 to add the flexibility to allow users to provide CUDA EP options in a flexible fashion. Note that this PR doesn't include the update for TRT options.
Before, the CUDA EP options are set within the parameters field:
```
...
parameters { key: "cudnn_conv_algo_search" value: { string_value: "0" } }
parameters { key: "gpu_mem_limit" value: { string_value: "4294967200" } }
...
```
After this enhancement, users are able to set any kinds of CUDA EP options just like the TRT EP:
```
optimization { execution_accelerators {
gpu_execution_accelerator : [ {
name : "cuda"
parameters { key: "cudnn_conv_use_max_workspace" value: "0" }
parameters { key: "use_ep_level_unified_stream" value: "1" }}
]
}}
```
For …
> enhancement: Dynamically updating CUDA EP options

- tools/gen_ort_dockerfile.py
Adding ORT patch from here: https://github.com/microsoft/onnxruntime/pull/20770
With build patch we used in a previous release here: https://github.com/triton-inference-server/onnxruntime_backend/commit/05d098d89f0455588fb85f0a22d97dd8ecc6cac9
In case the ORT release containing this fix does not match our timelines for getting r24.06 out.
> build: Add WAR for CUDA 12.5 build issue

- src/onnxruntime.cc
Added the missing `ort_api->AllocatorFree` to avoid memory leaks.
Before the fix, there will be memory leaks whenever GPU is enabled and ORT backend is using CUDA execution provider by default. This happens during model loading:
```
==1947== 399 bytes in 1 blocks are definitely lost in loss record 1,355 of 1,950
[2450](https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/98519216#L2450)==1947== at 0x484DE30: memalign (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
[2451](https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/98519216#L2451)==1947== by 0x484DF92: posix_memalign (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
[2452](https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/98519216#L2452)==1947== by 0x56E7EDF4: …
```
> fix: Fix ORT backend memory leak

- src/onnxruntime.cc
Cherry-picking for r24.07.
* Call AllocatorFree
* Handle return
> fix: Fix ORT backend memory leak (#261)

- src/onnxruntime.cc
Move each individual check of string input in model backend repos to the bakend repo. 
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
backend: https://github.com/triton-inference-server/backend/pull/101
tensorflow_backend: https://github.com/triton-inference-server/tensorflow_backend/pull/104
pytorch_backend: https://github.com/triton-inference-server/pytorch_backend/pull/136
onnxruntime_backend: https://github.com/triton-inference-server/onnxruntime_backend/pull/263
python_backend: https://github.com/triton-inference-server/python_backend/pull/370
- CI Pipeline ID:
17021222 and 17057045
Initially just to add missing string input tensor checks to python_backend. Refactored because …
> refactor: Refactor string input checks

- tools/gen_ort_dockerfile.py
This is a quick fix to tritonserver container backend. which fix non-found `libonnxruntime.so.1`
```
$ docker run --rm -it  tritonserver:24.08-py3-base bash -c "ldd backends/onnxruntime/libtriton_onnxruntime.so" | grep found
libtritonserver.so => not found
libonnxruntime.so.1 => not found
```
Related issue: https://github.com/microsoft/onnxruntime/issues/21763
> Hardcoding libonnxruntime.so.1 library name reference value

- tools/gen_ort_dockerfile.py
Goal: Support the ORT Backend on RHEL8 systems.
Server Changes: https://github.com/triton-inference-server/server/pull/7568
TensorRT Backend: https://github.com/triton-inference-server/tensorrt_backend/pull/98
TensorFlow: https://github.com/triton-inference-server/tensorflow_backend/pull/105
PyTorch Backend: https://github.com/triton-inference-server/pytorch_backend/pull/137
> build: RHEL8 PyTorch Backend

- tools/gen_ort_dockerfile.py
Hard coding by using symbolic link to point to the missed library in ONNX backend.
Ref: https://nvidia.slack.com/archives/CJN9422C9/p1723748846373309
Verified that this change is required for ORT version 1.19.2.
Example pipeline [here](https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/pipelines/18139020)
PS: This change required for ONNX versions 1.19.1 and 1.19.2.
> hardcoding sym link library reference for ONNX

- tools/gen_ort_dockerfile.py
TensorRT 10.5 support page: 
https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html
> Remove unsupported compute capabilities

- tools/gen_ort_dockerfile.py
Upgrade OPENVINO_VERSION_MAP in Onnxruntine backed. Also includes the fix for missing library after openvino upgrade.
> 24.10 Upgrade openvino version

- tools/gen_ort_dockerfile.py
Cherry pick changes from 24.10 branches to reflect changes in Openvino version and include support for TRT 10.5
> Update onnxruntime_backend after 24.10

- CMakeLists.txt
- tools/gen_ort_dockerfile.py
This PR enables support for Ubuntu 24.04 by adding a new job to the CI workflow.
> Enable support for Ubuntu 24.04

- tools/gen_ort_dockerfile.py
Switching to pre-defined NVIDIA Optimized Frameworks gpu codes in order to optimize compilation instructions for C++.
> build: CUDA_ARCHITECUTES: Update Dockerfile generation script for  codes

- tools/gen_ort_dockerfile.py
* Enable all-major CUDA architectures for non x86_64 builds.
* Hardcoding the value
Fixes TRI-30
> Define missed CUDA architectures for non x86_64 builds. (#318)
